#!/bin/sh

mkdir data/

scrapy crawl vixra

python crawlers/spiders/arxiv.py --category='hep-ph' --entries=1200
python crawlers/spiders/arxiv.py --category='gr-qc' --entries=1200
python crawlers/spiders/arxiv.py --category='astro-ph.CO' --entries=600
python crawlers/spiders/arxiv.py --category='astro-ph.GA' --entries=600
python crawlers/spiders/arxiv.py --category='astro-ph.HE' --entries=600
python crawlers/spiders/arxiv.py --category='quant-ph' --entries=2000
